apiVersion: v1
kind: Service
metadata:
  name: qutebapp-api-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 60917
      targetPort: 60917
  selector:
    app: dotnet
    role: backend